### ISSUE TITLE
Is this lib support low frequency ev detect?

### ISSUE THREAD

**Issue by b-y-f** [Plexflo/plexflo#7]
Is this lib support low frequency ev detect? like 1 hour0.5hour

**Comment by pranavraikote** [comment]
Can you please provide some more details? Is your question: "Will it detect EVs if the overall charging time is 0.5 hour?

**Comment by b-y-f** [comment]
Y

> Can you please provide some more details? Is your question: "Will it detect EVs if the overall charging time is 0.5 hour?

Yes, if my data is watt hour and interval is 30min or 1 hour, I find your model only work on high frequency dataset

**Comment by b-y-f** [comment]
And I tried on my half hourly dataset it give wrong results.

**Comment by pranavraikote** [comment]
Oh the interval, yeah as of now the Deep Learning model works well with data sampled at 1/60 Hz (in kWh unit). Also, the prediction interval is 15 minutes, you will get a prediction at the end of every 900 datapoints (correspond to 15 minutes).

We are in process of open sourcing models with various intervals in the coming weeks. Kindly mention the sampling rates and prediction intervals which will be appropriate for you and the community, and we shall work hard to implement and open source the same.

**Comment by b-y-f** [comment]
@pranavraikote Done with 30min? we'd like a demo
